# NXP Debian Linux SDK Distribution configuration for iMX and Layerscape MPU platforms

DISTRIB_NAME:    "NXP Debian Linux SDK"
DISTRIB_VERSION: "lsdk2512"
RELEASE_TYPE:    "external"


# default repo tag which can be overrided by specified tag
DEFAULT_REPO_TAG: "lf-6.12.20-2.0.0"

# default Debian version for target userland
DEBIAN_CODENAME: "trixie"
DEBIAN_VERSION:  "13"

# y if git information is needed
CONFIG_KEEP_GIT: n

# enable/disable custom packagegroups
# This feature is intended for advanced users.
# Improper configuration may lead to build failures
# or cause the system to operate incorrectly.
# It is strongly recommended not to modify this setting.
PKG_GROUPS_NETWORKING: y
PKG_GROUPS_UTILS: y
PKG_GROUPS_SECURITY: y
PKG_GROUPS_ML: y
PKG_GROUPS_GOPOINT: y
PKG_GROUPS_ROBOTICS: n

# default IMX if '-p' option is not specified, change to LS for Layerscape SoC
DEFAULT_SOC_FAMILY: IMX

# force build in docker environment
# must be 'y'
FORCE_BUILD_IN_DOCKER: y

# The URL for pre-built images
DISTRO_SVR_URL: "https://www.nxp.com/lgfiles/sdk"

# fuse provisioning
CONFIG_FUSE_PROVISIONING: n

# user can customize the default path of components source and build output path
DEFAULT_OUT_PATH: $FBDIR/build_${DISTRIB_VERSION}
DEFAULT_PKGDIR: $FBDIR/components_${DISTRIB_VERSION}


# default kernel config list
KERNEL_CONFIG:
  ARM64_LS:  "defconfig lsdk.config"
  ARM64_IMX: "imx_v8_defconfig"


# DPAA2 MC firmware version
MC_FW_VERSION:  "10.39.0"

# flexbuild repo list
repo:

# BSP component repositories
# --------------------------------------------------------------------------------------
  atf:
    url:  https://github.com/nxp-imx/imx-atf.git

  uboot:
    url:  https://github.com/nxp-imx/uboot-imx.git

  rcw:
    url:  https://github.com/nxp-qoriq/rcw.git

  mbedtls:
    url:  https://github.com/Mbed-TLS/mbedtls.git
    tag:  v3.6.4

  mc_utils:
    url:  https://github.com/nxp-qoriq/mc-utils.git
    tag:  mc_release_10.39.0

  mc_bin:
    url:  https://github.com/nxp-qoriq/qoriq-mc-binary.git
    tag:  mc_release_10.39.0

  ddr_phy_bin:
    url:  https://github.com/nxp-qoriq/ddr-phy-binary.git
    ver:  1dd5f83

  qe_ucode:
    url:  https://github.com/nxp-qoriq/qoriq-qe-ucode.git

  fm_ucode:
    url:  https://github.com/nxp-qoriq/qoriq-fm-ucode.git

  pfe_bin:
    url:  https://github.com/nxp-qoriq/qoriq-engine-pfe-bin.git

  phy_cortina:
    url:  https://github.com/nxp-qoriq/qoriq-firmware-cortina.git

  phy_inphi:
    url:  https://github.com/nxp-qoriq/qoriq-firmware-inphi.git

  imx_mkimage:
    url:  https://github.com/nxp-imx/imx-mkimage.git

  imx_sm:
    url:  https://github.com/nxp-imx/imx-sm.git

  imx_oei:
    url:  https://github.com/nxp-imx/imx-oei.git

# i.MX SECO firmware for i.MX 8QuadMax, 8QuadXPlus, and 8DXL reference boards
  seco_bin:
    url:  https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/imx-seco-5.9.4.1-0333596.bin

# i.MX System Controller Firmware for i.MX 8QuadMax, 8QuadXPlus, and 8DXL reference boards
  scfw_bin:
    url:  https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/imx-sc-firmware-1.18.0-654907b.bin

  firmware_imx_bin:
    url:  https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/firmware-imx-8.28-994fa14.bin
    md5:  2e4037eb1971d4be2e22b31cdf5bf50a
    # /lib/firmware for ddr,hdmi,dp,vpu,easrc,epdc,xcvr,xuvi

  imx_firmware:
    url:  https://github.com/NXP/imx-firmware.git
    # firmware for wifi/bt

#  i.MX 91, i.MX 93, i.MX 95, and i.MX 8ULP ELE Firmware
  fw_ele_bin:
    url:  https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/firmware-ele-imx-2.0.2-89161a8.bin

# i.MX 8ULP uPower firmware
  fw_upower_bin:
    url:  https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/firmware-upower-1.3.1.bin

# mcore demo
  imx8mm_mdemo:
    url:  https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/imx8mm-m4-demo-25.03.00.bin

  imx8mp_mdemo:
    url:  https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/imx8mp-m7-demo-25.03.00.bin

  imx8mq_mdemo:
    url:  https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/imx8mq-m4-demo-25.03.00.bin

  imx8mn_mdemo:
    url:  https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/imx8mn-m7-demo-25.03.00.bin

  imx8qm_mdemo:
    url:  https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/imx8qm-m4-demo-2.9.0.bin

  imx8ulp_mdemo:
    url:  https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/imx8ulp-m33-demo-25.03.00.bin

  imx93_mdemo:
    url:  https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/imx93-m33-demo-25.06.00.bin

  imx95_mdemo:
    url:  https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/imx95-m7-demo-25.06.00.bin



# kernel and modules git repositories
# --------------------------------------------------------------------------------------
  linux:
    url:  https://github.com/nxp-imx/linux-imx.git

  cryptodev_linux:
    url:  https://github.com/cryptodev-linux/cryptodev-linux.git
    tag:  cryptodev-linux-1.14

  lttng_modules:
    url:  https://github.com/lttng/lttng-modules.git
    tag:  v2.13.17

  mdio_proxy_module:
    url:  https://github.com/nxp-qoriq/mdio-proxy-module.git

  isp_vvcam_module:
    url:  https://github.com/nxp-imx/isp-vvcam.git

  nxp_wlan_bt:
    url:  https://github.com/nxp-imx/mwifiex.git



# networking component repositories
# --------------------------------------------------------------------------------------
  restool:
    url:  https://github.com/nxp-qoriq/restool.git

  fmc:
    url:  https://github.com/nxp-qoriq/fmc.git

  spc:
    url:  https://github.com/nxp-qoriq/spc.git

  tsntool:
    url:  https://github.com/nxp-qoriq/tsntool.git
    ver:  Real-Time-Edge-v3.2-202507

  dpdk:
    url:  https://github.com/nxp-qoriq/dpdk.git

  vpp:
    url:  https://github.com/nxp-qoriq/vpp.git

  ovs_dpdk:
    url:  https://github.com/nxp-qoriq/ovs-dpdk.git

  pktgen_dpdk:
    url:  https://github.com/pktgen/pktgen-dpdk.git
    tag:  pktgen-23.06.1

  mtcp_dpdk:
    url:  https://github.com/nxpmicro/mtcp.git

  aiopsl:
    url:  https://github.com/nxp-qoriq/aiopsl.git

  ceetm:
    url:  https://github.com/nxp-qoriq/ceetm.git

  dce:
    url:  https://github.com/nxp-qoriq/dce.git

  flib:
    url:  https://github.com/nxp-qoriq/flib.git

  fmlib:
    url:  https://github.com/nxp-qoriq/fmlib.git

  aquantia_fw_util:
    url:  https://github.com/nxp-qoriq/aquantia-firmware-utility.git

  gpp_aioptool:
    url:  https://github.com/nxp-qoriq/gpp-aioptool.git

  qbman_userspace:
    url:  https://github.com/nxp-qoriq/qbman_userspace.git

  eth_config:
    url:  https://github.com/nxp-qoriq/eth-config.git


# security component repositories
# --------------------------------------------------------------------------------------
  cst:
    url:  https://github.com/nxp-qoriq/cst.git

  openssl:
    url:  https://github.com/openssl/openssl.git
    tag:  openssl-3.5.0

  libpkcs11:
    url:  https://github.com/nxp-qoriq/libpkcs11.git
    ver:  lf-6.6.52-2.2.0

  secure_obj:
    url:  https://github.com/nxp-qoriq/secure_obj.git
    ver:  lf-6.6.52-2.2.0

  optee_os:
    url:  https://github.com/nxp-qoriq/optee_os.git

  optee_client:
    url:  https://github.com/nxp-qoriq/optee_client.git

  optee_test:
    url:  https://github.com/nxp-qoriq/optee_test.git

  crconf:
    url:  https://github.com/Thermi/crconf.git
    tag:  0.4

  keyctl_caam:
    url:  https://github.com/nxp-imx/keyctl_caam.git

  imx_smw:
    url:  https://github.com/nxp-imx/imx-smw.git

  ecc_example:
    url:  https://github.com/nxp/plug-and-trust.git
    tag:  v04.07.00

  openssl_provider_se05x:
    url:  https://github.com/NXPPlugNTrust/se05x-openssl-provider.git
    tag:  v01.00.02

  imx_secure_enclave:
    url:  https://github.com/nxp-imx/imx-secure-enclave.git



# graphics component repositories
# --------------------------------------------------------------------------------------
  wayland:
    url:  https://gitlab.freedesktop.org/wayland/wayland.git
    tag:  1.22.0

  wayland_protocols:
    url:  https://github.com/nxp-imx/wayland-protocols-imx.git

  weston:
    url:  https://github.com/nxp-imx/weston-imx.git

  libdrm:
    url:  https://github.com/nxp-imx/libdrm-imx.git

  gpu_viv_bin:
    url:  https://www.nxp.com/lgfiles/sdk/lsdk2512/imx-gpu-viv-6.4.11.p3.2-aarch64-6.12.20.bin

  gputop:
    url:  https://github.com/nxp-imx/imx-gputop.git

  apitrace:
    url:  https://github.com/nxp-imx/apitrace-imx.git

  libgpuperfcnt_bin:
    url:  https://www.nxp.com/lgfiles/sdk/lsdk2512/libgpuperfcnt-6.4.11.p3.2-aarch64-6.12.20.bin
#
#  i.MX Graphics G2D libraries for i.MX 8
  imx_gpu_g2d_bin:
    url:  https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/imx-gpu-g2d-6.4.11.p3.2-aarch64-3c5e429.bin

# i.MX G2D library for i.MX 8 Auto SoC with DPU blitter engine
  imx_dpu_g2d_bin_v1:
    url:  https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/imx-dpu-g2d-v1-2.4.0.0-9e8bbf1.bin

# i.MX G2D library for i.MX 9 SoC with DPU blitter engine
  imx_dpu_g2d_bin_v2:
    url:  https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/imx-dpu-g2d-v2-2.4.0.0-9e8bbf1.bin

  mali_imx_bin:
    url:  https://www.nxp.com/lgfiles/sdk/lsdk2512/mali-imx-r54.0-aarch64-6.12.20.bin
    md5:  7ebc277f1fb66774bf4ff9ec2cc20e38

  imx_pxp_g2d:
    url:  https://github.com/nxp-imx/imx-g2d-pxp.git

  imx_g2d_samples:
    url:  https://github.com/nxp-imx/g2d-samples.git

  cogl:
    url:  https://gitlab.gnome.org/Archive/cogl.git
    tag:  1.22.8

  clutter_gst:
    url:  https://gitlab.gnome.org/Archive/clutter-gst.git
    tag:  3.0.27

  vulkan_headers:
    url: https://github.com/KhronosGroup/Vulkan-Headers.git
    ver: vulkan-sdk-1.3.275.0

  vkmark:
    url: https://github.com/vkmark/vkmark.git
    ver: ab6e6f3



# multimedia component repositories
# --------------------------------------------------------------------------------------
# i.MX VPU Hantro libraries for i.MX 8M Quad, 8M Mini, and 8M Plus
  vpu_hantro_bin:
    url:  https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/imx-vpu-hantro-1.37.0-deec65e.bin

# i.MX VPU Hantro VC8000E Encoder libraries for i.MX 8M plus
  vpu_hantro_vc_bin:
    url:  https://www.nxp.com/lgfiles/sdk/lsdk2512/imx-vpu-hantro-vc-1.10.2-aarch64-6.12.20.bin

# i.MX VPU Hantro deamon binary for i.MX 8M Quad, 8M Mini, and 8M Plus
  vpu_hantro_daemon_tar:
    url:  https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/imx-vpu-hantro-daemon-1.6.0-cc9a838.tar.gz

#
#  basler_camera_bin:
#    url:  https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/basler-camera-4.2.2.25.2-dd86758.bin

# i.MX 8M Plus ISP SDK
  imx_isp_bin:
    url:  https://www.nxp.com/lgfiles/sdk/lsdk2512/isp-imx-4.2.2.25.2-aarch64-6.12.20.bin

  gstreamer:
    url:  https://github.com/nxp-imx/gstreamer.git

  gst_python_tar:
    url:  https://gstreamer.freedesktop.org/src/gst-python/gst-python-1.26.0.tar.xz

  gst_plugins_base:
    url:  https://github.com/nxp-imx/gst-plugins-base.git

  gst_plugins_good:
    url:  https://github.com/nxp-imx/gst-plugins-good.git

  gst_plugins_bad:
    url:  https://github.com/nxp-imx/gst-plugins-bad.git

  gst_plugins_ugly:
    url:  https://github.com/GStreamer/gst-plugins-ugly.git
    ver: 499d3cd

  imx_gst_plugin:
    url:  https://github.com/nxp-imx/imx-gst1.0-plugin.git

  imx_alsa_plugin:
   url:   https://github.com/nxp-imx/imx-alsa-plugins.git

  imx_lib:
   url:  https://github.com/nxp-imx/imx-lib.git
#md5:  d004ec6ac6a330c14632bb97bbedbf93

  alsa_lib:
    url:  https://github.com/alsa-project/alsa-lib.git
    tag:  v1.2.13

#  SOF firmware architecture is based on Zephyr RTOS
  sof_zephyr_tar:
    url:  https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/sof-zephyr-2.13.0-3d67d3f.tar.gz
    md5:  2a6d226d36bbecf8fcb455dc037c44ee

# i.MX optimized Audio and Video core codec libraries
  imx_codec_bin:
    url:  https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/imx-codec-4.10.0-464e9d8.bin

# DSP firmware
  imx_dsp_bin:
    url:  https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/imx-dsp-2.1.10-ea4fe3f.bin
    md5:  5400a078994256004a37be2ed7d187d4

# DSP AACPlus decoder
  imx_dsp_codec_ext_bin:
    url: https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/imx-dsp-codec-ext-2.1.8.bin

# NXP Asynchronous Sample Rate Converter
  imx_dspc_asrc_bin:
    url: https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/imx-dspc-asrc-1.0.2-ce4ae5a.bin

# i.MX optimized core parser
  imx_parser_bin:
    url: https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/imx-parser-4.10.0-e8a7ec7.bin

# NXP PDM to PCM Software Decimation SIMD Library
  imx_sw_pdm_bin:
    url: https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/imx-sw-pdm-1.0.3.bin

  imx_vpuwrap:
    url: https://github.com/nxp/imx-vpuwrap.git

  cheese:
    url: https://gitlab.gnome.org/Archive/cheese.git
    tag: 43.0

  libcamera:
    url: https://github.com/nxp-imx/libcamera.git

  neo_ipa_uguzzi:
    url:  https://github.com/nxp-imx/neo-ipa-uguzzi.git


# generic component repositories
# --------------------------------------------------------------------------------------
  imx_test:
    url: https://github.com/nxp-imx/imx-test.git

  firmwared:
    url: https://github.com/teg/firmwared.git
    ver: 2e6b5db

  wireless_regdb_tar:
    url: https://www.kernel.org/pub/software/network/wireless-regdb/wireless-regdb-2025.02.20.tar.xz
    md5: 7454c55208ca51bae6461ca7932559ab

#  buildroot:
#    url:  https://github.com/buildroot/buildroot.git
#    tag:  2024.02.2

#  yocto_poky:
#    url:  https://git.yoctoproject.org/poky.git
#    tag:  scarthgap-5.0.2

#  yocto_oe:
#    url:  https://github.com/openembedded/meta-openembedded.git
#    branch: scarthgap


# eIQ AI/ML components
# --------------------------------------------------------------------------------------
  tim_vx:
    url: https://github.com/nxp-imx/tim-vx-imx.git

  tvm:
    url: https://github.com/nxp-imx/eiq-tvm-imx.git

  tflite:
    url: https://github.com/nxp-imx/tensorflow-imx.git

  model_mobv1:
    url: https://storage.googleapis.com/download.tensorflow.org/models/mobilenet_v1_2018_08_02/mobilenet_v1_1.0_224_quant.tgz

  tflite_vx_delegate:
    url: https://github.com/nxp-imx/tflite-vx-delegate-imx.git

  tflite_ethosu_delegate:
    url: https://github.com/nxp-imx/tflite-ethosu-delegate-imx.git

  ethosu_driver_stack:
    url: https://github.com/nxp-imx/ethos-u-driver-stack-imx.git

  ethosu_firmware:
    url: https://github.com/nxp-imx/ethos-u-firmware.git

  ethosu_vela:
    url: https://github.com/nxp-imx/ethos-u-vela.git

  nnstreamer:
    url: https://github.com/nnstreamer/nnstreamer.git
    ver: 8070609

  nnstreamer_edge:
    url: https://github.com/nnstreamer/nnstreamer-edge.git
    ver: 2bf50d5

  nnshark:
    url: https://github.com/nxp-imx/nnshark.git

  ssat:
    url: https://github.com/myungjoo/ssat.git
    ver: v1.2.0

  eiq_examples:
    url: https://github.com/nxp-imx/eiq-example.git

  pytorch:
    url: https://github.com/nxp-imx/pytorch-release.git

  flatbuffers:
    url: https://github.com/google/flatbuffers.git
    ver: v24.3.25

  neutron:
    url:  https://github.com/nxp-imx/neutron.git

  tflite_neutron_delegate:
    url:  https://github.com/nxp-imx/tflite-neutron-delegate.git


# NXP GoPoint Demo Experience components
# --------------------------------------------------------------------------------------
  imx_demo_experience:
    url: https://github.com/nxp-imx-support/nxp-demo-experience.git

  imx_nnstreamer_examples:
    url: https://github.com/nxp-imx/nxp-nnstreamer-examples.git
    ver: b8dafc1

  imx_demos_list:
    url: https://github.com/nxp-imx-support/nxp-demo-experience-demos-list.git

  imx_smart_kitchen:
    url: https://github.com/nxp-imx-support/smart-kitchen.git
    ver: 1f42ace

  imx_smart_fitness:
    url: https://github.com/nxp-imx-support/imx-smart-fitness.git
    ver: 5ac9a93

  nxp_afe:
    url: https://github.com/nxp-imx/nxp-afe.git

  imx_voiceui:
    url: https://github.com/nxp-imx/imx-voiceui.git

  nxp_demo_experience_assets:
    url: https://github.com/nxp-imx-support/nxp-demo-experience-assets.git

  imx_video_to_texture:
    url: https://github.com/nxp-imx-support/imx-video-to-texture.git
    ver: ee77a45

  imx_voiceplayer:
    url: https://github.com/nxp-imx-support/imx-voiceplayer.git
    ver: ab1304a

  imx_ebike_vit:
    url: https://github.com/nxp-imx-support/imx-ebike-vit.git
    ver: 7216521

  gtec_demo_framework:
    url: https://github.com/nxp-imx/gtec-demo-framework.git
    tag: 6.5.0

  imx_ele:
    url: https://github.com/nxp-imx-support/imx-ele-demo.git
    ver: 2134fee

  imx_video2texture:
    url: https://github.com/nxp-imx-support/imx-video-to-texture.git
    ver: ee77a45
